### ISSUE TITLE
Duplicated modules in psci

### ISSUE THREAD

**Issue by Softsapiens** [parsonsmatt/purs-architecture-tutorial#3]
Hi,
Do you know why is not possible to work with psci in this project due to:
"Error found:
Module Control.Alt has been defined multiple times."

It seems there is a lot of modules loaded twice¿?
Find this reference 
https://github.com/purescript/purescript/issues/818
but I don't see the solution in this case.

Thanks in advance for your help,
Dani

**Comment by parsonsmatt** [comment]
That's odd -- I just did `psci` in the directory and it is working without any issues. Try using the newest version of PureScript and potentially deleting the local `bower_components` to clear the dependencies.

**Comment by Softsapiens** [comment]
Totally agree.
I'm using the last version of psc in an OSX environment. And works fine with other projects.

I tried 'pulp psci' and 'psci' with the same result, the repl works, but when I try to import a module, the explained error appears.
Have you tried to import Prelude, for example? Or any other module?

**Comment by parsonsmatt** [comment]
Well, I tried on my laptop, and had the same problem you're mentioning. I deleted the `.psci` file and tried `pulp psci` and now it is working to import modules. ¯_(ツ)_/¯

**Comment by Softsapiens** [comment]
Yes!

Sorry for the delay and thanks for the help

**Comment by parsonsmatt** [comment]
Cool! Is it working for you now then?

**Comment by Softsapiens** [comment]
Yep, the project was working all the time, the only 'problem' was the repl.

Thanks again

**Comment by parsonsmatt** [comment]
Awesome :)
